spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_simulator_db
    username: nadezhda
    password: nadezhda
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    show-sql: true
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true





